import {
  Github,
  Linkedin,
  Twitter,
  Code2,
  FlaskConical,
  Zap,
  Star,
  Target,
  BookOpen,
  FileText,
  Globe,
  Tag,
} from "lucide-react";

export const PLATFORMS = [
  {
    key: "githubId",
    label: "GitHub",
    placeholder: "octocat",
    icon: <Github size={15} />,
    color: "148,163,184",
    url: (u) => `https://github.com/${u}`,
  },
  {
    key: "linkedIn",
    label: "LinkedIn",
    placeholder: "john-doe",
    icon: <Linkedin size={15} />,
    color: "10,102,194",
    url: (u) => `https://linkedin.com/in/${u}`,
  },
  {
    key: "twitterId",
    label: "Twitter / X",
    placeholder: "johndoe",
    icon: <Twitter size={15} />,
    color: "29,161,242",
    url: (u) => `https://twitter.com/${u}`,
  },
  {
    key: "leetcodeId",
    label: "LeetCode",
    placeholder: "lc_handle",
    icon: <Code2 size={15} />,
    color: "255,161,22",
    url: (u) => `https://leetcode.com/${u}`,
  },
  {
    key: "codechefId",
    label: "CodeChef",
    placeholder: "cc_handle",
    icon: <FlaskConical size={15} />,
    color: "90,60,10",
    url: (u) => `https://codechef.com/users/${u}`,
  },
  {
    key: "codeforcesId",
    label: "Codeforces",
    placeholder: "cf_handle",
    icon: <Zap size={15} />,
    color: "24,119,242",
    url: (u) =>
      `https://codeforces.com/profile/${u}`,
  },
  {
    key: "hackerRankId",
    label: "HackerRank",
    placeholder: "hr_handle",
    icon: <Star size={15} />,
    color: "41,183,88",
    url: (u) =>
      `https://hackerrank.com/profile/${u}`,
  },
  {
    key: "kaggleId",
    label: "Kaggle",
    placeholder: "kaggle_handle",
    icon: <Target size={15} />,
    color: "32,186,218",
    url: (u) => `https://kaggle.com/${u}`,
  },
  {
    key: "mediumId",
    label: "Medium",
    placeholder: "medium_handle",
    icon: <BookOpen size={15} />,
    color: "255,255,255",
    url: (u) => `https://medium.com/@${u}`,
  },
  {
    key: "devToId",
    label: "Dev.to",
    placeholder: "dev_handle",
    icon: <FileText size={15} />,
    color: "99,102,241",
    url: (u) => `https://dev.to/${u}`,
  },
  {
    key: "portfolio",
    label: "Portfolio",
    placeholder: "https://site.com",
    icon: <Globe size={15} />,
    color: "168,85,247",
    url: (u) => u,
  },
  {
    key: "npmId",
    label: "npm",
    placeholder: "npm_username",
    icon: <Tag size={15} />,
    color: "203,65,65",
    url: (u) => `https://npmjs.com/~${u}`,
  },
];
